# Exodus Category
level = "category"
id = "03"
title = "Exodus"
beg = 9
count = 6

[image]
filename = "00-02d.png"

# Stories in this category
[[stories]]
id = "09"
title = "God Calls Moses"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-09-01.jpg"

[[stories]]
id = "10"
title = "The Ten Plagues"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-10-01.jpg"

[[stories]]
id = "11"
title = "The Passover"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-11-01.jpg"

[[stories]]
id = "12"
title = "The Exodus"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-12-01.jpg"

[[stories]]
id = "13"
title = "God's Covenant with Israel"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-13-01.jpg"

[[stories]]
id = "14"
title = "Wandering in the Wilderness"
image = "https://cdn.door43.org/obs/jpg/360px/obs-en-14-01.jpg"
